name: Build windows

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            platform: windows
    defaults:
      run:
        shell: msys2 {0}
            
    steps:
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          install: >-
            make
            diffutils
            gcc
            yasm
            pkg-config
              
      - name: Cache FFmpeg build
        id: ffmpeg-cache
        uses: actions/cache@v4
        with:
          path: ffmpeg-${{ matrix.platform }}
          key: ffmpeg-${{ matrix.platform }}-7.1.2-v0.1

      - name: Download and build FFmpeg (if not cached)
        if: steps.ffmpeg-cache.outputs.cache-hit != 'true'
        run: |
          OS=${{ matrix.platform }}
          
          curl -L -o ffmpeg-7.1.2.tar.bz2 https://ffmpeg.org/releases/ffmpeg-7.1.2.tar.bz2
          tar -xjf ffmpeg-7.1.2.tar.bz2
          rm ffmpeg-7.1.2.tar.bz2
          cd ffmpeg-7.1.2

          ./configure --prefix=./ffmpeg-$OS \
              --disable-avdevice --disable-postproc \
              --enable-decoder=h264 --enable-decoder=hevc --enable-decoder=av1 \
              --enable-swscale --enable-filter=scale --enable-avformat --enable-avcodec --enable-avutil --enable-swresample \
              --enable-gpl --disable-static --enable-shared
              
          make -j$(nproc)
          make install
          mv ffmpeg-$OS ../ffmpeg-$OS

      - name: Upload ffmpeg artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-${{ matrix.platform }}
          path: ffmpeg-${{ matrix.platform }}
    
      # - name: Checkout codes
      #   uses: actions/checkout@v5.0.0
      #   with:
      #       path: scrcpy-mask
