name: Build scrcpy-mask

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        include:
          - os: macos-latest
            platform: macos-arm64
            
    steps:
      - name: Download and build FFmpeg (if not cached)
        if: steps.ffmpeg-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          OS=${{ matrix.platform }}
          
          curl -L -o FFmpeg-n7.1.2.tar.gz https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n7.1.2.tar.gz
          tar -xzf FFmpeg-n7.1.2.tar.gz
          rm FFmpeg-n7.1.2.tar.gz
          mv FFmpeg-n7.1.2 ffmpeg-7.1.2
          cd ffmpeg-7.1.2

          ./configure --prefix=./ffmpeg-$OS \
              --disable-all --disable-doc --disable-iconv \
              --enable-decoder=h264 --enable-decoder=hevc --enable-decoder=av1 \
              --enable-swscale --enable-avformat --enable-avcodec --enable-avutil --enable-swresample \
              --enable-gpl --enable-static --disable-shared
              
          make -j$(sysctl -n hw.ncpu)
          make install
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          path: ffmpeg-7.1.2/ffmpeg-macos-arm64
          name: ffmpeg-macos-arm64
