name: Build scrcpy-mask (Windows)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            platform: windows-x64
            
    steps:
      - name: Set up msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: Set up msys
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            make
            diffutils
            yasm
            pkg-config
          path-type: inherit

      - name: Verify tools
        shell: msys2 {0}
        run: |
          cl.exe /?
          nasm -v
          perl -v
          make -v

      - name: Download and build FFmpeg (if not cached)
        if: steps.ffmpeg-cache.outputs.cache-hit != 'true'
        shell: msys2 {0}
        run: |
          OS=${{ matrix.platform }}
          
          curl -L -o FFmpeg-n7.1.2.tar.gz https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n7.1.2.tar.gz
          tar -xzf FFmpeg-n7.1.2.tar.gz
          rm FFmpeg-n7.1.2.tar.gz
          mv FFmpeg-n7.1.2 ffmpeg-7.1.2
          cd ffmpeg-7.1.2

          ./configure --prefix=./ffmpeg-$OS \
              --disable-all --disable-doc --disable-iconv \
              --toolchain=msvc \
              --enable-decoder=h264 --enable-decoder=hevc --enable-decoder=av1 \
              --enable-swscale --enable-avformat --enable-avcodec --enable-avutil --enable-swresample \
              --enable-gpl --disable-static --enable-shared

          make -j$(nproc)
          make install
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          path: ffmpeg-7.1.2/ffmpeg-windows-x64
          name: ffmpeg-windows-x64
